# Generated by Django 4.1.9 on 2023-05-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
