# Generated by Django 4.1.9 on 2023-05-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_embedded_options_embedded_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedded',
            name='pump_on',
            field=models.BooleanField(default=True),
        ),
    ]
