# Generated by Django 4.1.9 on 2023-05-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_embedded_pump_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=255)),
                ('temperature', models.FloatField(max_length=255)),
                ('humidity', models.FloatField(max_length=255)),
                ('light', models.FloatField(max_length=255)),
                ('rainfall', models.FloatField(max_length=255)),
                ('soil_moisture', models.FloatField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
        migrations.AlterField(
            model_name='embedded',
            name='pump_on',
            field=models.BooleanField(default=False),
        ),
    ]
