# Generated by Django 4.1.9 on 2023-05-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_crops_alter_embedded_pump_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crops',
            old_name='humidity',
            new_name='soil_moisture_max',
        ),
        migrations.RenameField(
            model_name='crops',
            old_name='light',
            new_name='soil_moisture_min',
        ),
        migrations.RemoveField(
            model_name='crops',
            name='rainfall',
        ),
        migrations.RemoveField(
            model_name='crops',
            name='soil_moisture',
        ),
        migrations.RemoveField(
            model_name='crops',
            name='temperature',
        ),
    ]
