# Generated by Django 4.1.9 on 2023-05-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_humidity_crops_soil_moisture_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crops',
            options={},
        ),
        migrations.RemoveField(
            model_name='crops',
            name='created',
        ),
        migrations.RemoveField(
            model_name='crops',
            name='updated',
        ),
    ]
