# Generated by Django 4.1.9 on 2023-05-20 11:23

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_crops_options_remove_crops_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['-creation_date']},
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='user_Img',
        ),
        migrations.AddField(
            model_name='userimage',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userimage',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
