# Generated by Django 4.1.9 on 2023-05-20 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userimage_options_remove_userimage_user_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='name',
        ),
    ]
