# Generated by Django 4.1.9 on 2023-05-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_userimage_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=255)),
                ('soil_moisture_min', models.FloatField(max_length=255)),
                ('soil_moisture_max', models.FloatField(max_length=255)),
            ],
        ),
    ]
