# Generated by Django 4.1.9 on 2023-05-24 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_selectedcrop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedcrop',
            name='crop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.crops'),
        ),
    ]
