# Generated by Django 4.1.9 on 2023-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_crop_crops_crop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_plant', models.CharField(max_length=255)),
                ('confidence', models.FloatField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='selectedcrop',
            name='soil_moisture_max',
            field=models.FloatField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='selectedcrop',
            name='soil_moisture_min',
            field=models.FloatField(auto_created=True),
        ),
    ]
