# Generated by Django 4.1.9 on 2023-05-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_reportplant_alter_selectedcrop_soil_moisture_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportplant',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
