# Generated by Django 4.1.9 on 2023-05-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_reportplant_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportplant',
            old_name='predicted_plant',
            new_name='plant_name',
        ),
        migrations.AlterField(
            model_name='selectedcrop',
            name='soil_moisture_max',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='selectedcrop',
            name='soil_moisture_min',
            field=models.FloatField(max_length=255),
        ),
    ]
